### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by mkleinbort-capgemini** [xl402/node#5]
Hello, 

Amazing project.

Could you add an example? 

E.g. titanic dataset.

**Comment by xl402** [comment]
Certainly. We have used NODE on two datasets, both found on Kaggle: the store item demand forecast and the fraud detection dataset. Code can be found on

https://github.com/xl402/neural-oblivious-decision-ensembles/blob/experiments/node/experiments/store_demand/node_experiment.py

Or you can just check-out the branch ‘experiments’ for the full comparison.

Best,

Tom

**Comment by mkleinbort-capgemini** [comment]
Thank you.
